
from fastapi import APIRouter, WebSocket
import os
from contextlib import suppress
import json
import numpy as np
import base64
import aiohttp
from vad_utils import VAD_Amp
from statistics import mean
from controller.config import get_openai_api_key, get_elevenlabs_api_key, get_elevenlabs_model
import time
import asyncio
import wave
import tempfile
from pathlib import Path
from openai import OpenAI
from groq import AsyncGroq
import uuid
import shutil
router = APIRouter()

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")

client = AsyncGroq(api_key=GROQ_API_KEY)

class ConnectionManager:
    """Tracks active WebSocket connections and handles safe connect/close."""
    def __init__(self) -> None:
        self.active_connections = set()

    async def connect(self, websocket: WebSocket) -> None:
        await websocket.accept()
        self.active_connections.add(websocket)
        print(f"chatbot connected (active={len(self.active_connections)})")

    async def safe_close(self, websocket: WebSocket, code: int = 1000) -> None:
        with suppress(Exception):
            await websocket.close(code=code)

    def disconnect(self, websocket: WebSocket) -> None:
        if websocket in self.active_connections:
            self.active_connections.discard(websocket)
            print(f"chatbot disconnected (active={len(self.active_connections)})")

manager = ConnectionManager()

class InterractionSession:
    def __init__(self, websocket):        
        self.summary = ""
        self.websocket = websocket
        self.data_array = []
        self.voiced_confidences = []
        self.big_chunk = b""
        self.start_looking = False
        self.sd_duration = 20 # TODO: SAME HERE int(os.environ.get("SD_DURATION"))  # the duration of audio on which the process should decide if silence long enough to be triggered
        self.sd_threshold = 300 # TODO: REMOVE THIS HARDCODING#int(os.environ.get("SD_THRESHOLD"))  # the probabilty score of voice in the audio" on which the process should decide if silence long enough to be triggered
        self.conversation = []
        self.introduced = False #flag to check if the assistant has introduced itself. once done, it is set to true
        self.start_looking = False #flag used to start silence detection
        self.sd_duration = int(os.environ.get('SD_DURATION')) #the duration of audio on which the process should decide if silence long enough to be triggered
        self.sd_threshold = int(os.environ.get('SD_THRESHOLD')) #the "probabilty score of voice in the audio" on which the process should decide if silence long enough to be triggered
        self.psd_duration = int(os.environ.get('PSD_DURATION')) #if the average VAD.AMP score over the last n (Phrase start Detection Duration) confidences is more than the Phrase Start Detection Threshold, User has started speaking 
        self.psd_threshold = int(os.environ.get('PSD_THRESHOLD')) # if the average VAD.AMP score over the last n (Phrase start Detection Duration) confidences is more than the Phrase Start Detection Threshold, User has started speaking 
        self.processing = False #boolean storing if a response has already been generated by the llm and is inthe process of being converted to audio and sent to user
        self.last_message = False

    async def push_audio(self, audio_bytes):
        if not self.summary :
            print("no summary")
            return

        if not self.introduced:
            
            self.processing = True
            greeting_messages = [
                {"text": "Whoa, looks like somebody wants to join the conversation!", "voice": "male"},
                {"text": "Amazing! Let's let them in!", "voice": "female"}
            ]
            
            # Save hardcoded introduction message to conversation history
            self.conversation.extend([
                {"speaker": "David", "text": "Whoa, looks like somebody wants to join the conversation!"},
                {"speaker": "Emma", "text": "Amazing! Let's let them in!"}
            ])
            
            # Send combined audio of both AI introductions to the user
            greeting_audio_base64 = await generate_combined_ai_speech_with_elevenlabs(greeting_messages)

            await self.websocket.send_text(json.dumps({
                "type": "response",
                "audio": {
                    "base64Wav": greeting_audio_base64
                }
            }))
            self.introduced = True
            self.processing = False

        if self.introduced and not self.processing: 
            self.big_chunk += audio_bytes
        
        if len(self.big_chunk) > 3072 : #chunks sent by twilio are much smaller than what is needed for Voice Activity Detection to perform operations, thus a big chunk is used to keep a cache of all chunks being recieved and once this cache is big enough (more than 3072), the chunks are proccessed and the cache is cleared.
            self.data_array.append(self.big_chunk)
            amplitude, VAD_confidence = VAD_Amp(self.big_chunk) #This function returns amplitude and voice activity confidence
            self.big_chunk = b''
            new_confidence = VAD_confidence*amplitude #custom confidence score (V.AMP) is created as a product of amplitude and voice activity confidence
            self.voiced_confidences.append(new_confidence)
    
        if len(self.voiced_confidences[-self.psd_duration:])!= 0 and mean(self.voiced_confidences[-self.psd_duration:]) > self.psd_threshold: #if the average V.AMP score over the last n (Phrase start Detection Duration) confidences is more than the Phrase Start Detection Threshold, User has started speaking 
            print("started speaking")
            await self.websocket.send_text(json.dumps({
                "type": "clear"
            }))  #if interrupt is turned on and the candidate said something clear or stop any response being played over the socket
            self.start_looking = True #start looking for silence
    
        if self.start_looking is True and len(self.voiced_confidences) > self.sd_duration and mean(self.voiced_confidences[-self.sd_duration:]) < self.sd_threshold : #if silence detection has been triggered and length of the voiced confidences array is more than the silence detection duration set and average of the last n (Silence Detection Duration) elements of the voiced confidences array is less than the Silence Detection Threshold, it means sufficient duration of silence has been detected.
            print("silence detected")
            self.start_looking = False
            self.processing = True
            await self.websocket.send_text(json.dumps({
                "type": "processing"
            }))

            transcribed_text = await transcribe_audio_groq(b''.join(self.data_array))
            print("transcribing")
            llm_response, elevenlabs_respons = await generate_podcast_response(self.summary, self.conversation, transcribed_text) 
            
            if llm_response.get("disconnect_trigger") :
                self.last_message = True

            await self.websocket.send_text(json.dumps({
                "type": "clear"
            }))
            await self.websocket.send_text(json.dumps({
                "type": "response",
                "audio": {
                    "base64Wav": elevenlabs_respons
                }
            }))
            if self.last_message :
                await self.close_connection()
            
            self.processing = False
            self.data_array = []

    async def close_connection(self):
        await self.websocket.close()


async def transcribe_audio(audio_bytes):
    """Transcribe raw PCM16 audio bytes using OpenAI SDK.

    Steps:
    - Wrap PCM16 bytes into a mono 48 kHz WAV file
    - Save to a temporary file under data/temp
    - Use OpenAI Python SDK to transcribe (gpt-4o-transcribe)
    - Clean up temp file
    """
    if not audio_bytes:
        return ""
    SAMPLE_RATE = 48000
    NUM_CHANNELS = 1
    SAMPLE_WIDTH_BYTES = 2
    temp_dir = Path("data/temp")
    temp_dir.mkdir(parents=True, exist_ok=True)
    wav_path = None
    try:
        cur_time = time.time()
        # Create a unique temp WAV file path
        wav_fd, wav_path_str = tempfile.mkstemp(prefix="ws_audio_", suffix=".wav", dir=str(temp_dir))
        os.close(wav_fd)
        wav_path = Path(wav_path_str)
        # Write WAV header + frames
        with wave.open(str(wav_path), 'wb') as wf:
            wf.setnchannels(NUM_CHANNELS)
            wf.setsampwidth(SAMPLE_WIDTH_BYTES)
            wf.setframerate(SAMPLE_RATE)
            wf.writeframes(audio_bytes)

        # # Save a permanent copy to the current working directory for manual listening/debugging
        # try:
        #     ts = time.strftime('%Y%m%d_%H%M%S')
        #     rand = str(uuid.uuid4())[:8]
        #     cwd_save_path = Path.cwd() / f"ws_audio_{ts}_{rand}.wav"
        #     shutil.copyfile(str(wav_path), str(cwd_save_path))
        #     print(f"Saved recorded WAV to: {cwd_save_path}")
        # except Exception as save_err:
        #     print(f"Failed to save a local WAV copy: {save_err}")

        # Use OpenAI SDK in a worker thread to avoid blocking the event loop
        def _do_transcribe(path: Path) -> str:
            client = OpenAI(api_key=get_openai_api_key())
            with open(str(path), "rb") as f:
                result = client.audio.transcriptions.create(
                    model="gpt-4o-transcribe",
                    file=f
                )
            # The SDK returns an object with .text
            return getattr(result, "text", "") or ""

        text = await asyncio.to_thread(_do_transcribe, wav_path)
        text = (text or "").strip()
        print(f"Transcription took {time.time() - cur_time:.2f} seconds; length={len(audio_bytes)} bytes")
        print(f"Transcription result: {text}")
        return text
    except Exception as e:
        print(f"Transcription error: {e}")
        return ""
    finally:
        with suppress(Exception):
            if wav_path and wav_path.exists():
                os.remove(str(wav_path))

async def transcribe_audio_groq(audio_bytes):
    """Transcribe raw PCM16 audio bytes using Groq Async SDK.

    Mirrors transcribe_audio: wraps bytes in a mono 48 kHz WAV temp file,
    saves a permanent copy for debugging, calls Groq, returns text.
    """
    if not audio_bytes:
        return ""
    SAMPLE_RATE = 48000
    NUM_CHANNELS = 1
    SAMPLE_WIDTH_BYTES = 2
    temp_dir = Path("data/temp")
    temp_dir.mkdir(parents=True, exist_ok=True)
    wav_path = None
    try:
        cur_time = time.time()
        wav_fd, wav_path_str = tempfile.mkstemp(prefix="ws_audio_", suffix=".wav", dir=str(temp_dir))
        os.close(wav_fd)
        wav_path = Path(wav_path_str)
        with wave.open(str(wav_path), 'wb') as wf:
            wf.setnchannels(NUM_CHANNELS)
            wf.setsampwidth(SAMPLE_WIDTH_BYTES)
            wf.setframerate(SAMPLE_RATE)
            wf.writeframes(audio_bytes)

        # # Save a permanent copy locally for listening/debugging
        # try:
        #     ts = time.strftime('%Y%m%d_%H%M%S')
        #     rand = str(uuid.uuid4())[:8]
        #     cwd_save_path = Path.cwd() / f"ws_audio_groq_{ts}_{rand}.wav"
        #     shutil.copyfile(str(wav_path), str(cwd_save_path))
        #     print(f"Saved recorded WAV (Groq) to: {cwd_save_path}")
        # except Exception as save_err:
        #     print(f"Failed to save a local WAV copy (Groq): {save_err}")

        text = ""
        try:
            with open(str(wav_path), "rb") as f:
                transcription = await client.audio.transcriptions.create(
                    file=f,
                    model="distil-whisper-large-v3-en",
                    response_format="verbose_json",
                    timestamp_granularities=["word", "segment"],
                )
            text = getattr(transcription, "text", "") or ""
        finally:
            # Best-effort close; depends on SDK implementation
            with suppress(Exception):
                close_coro = getattr(client, "close", None)
                if callable(close_coro):
                    await close_coro()  
            with suppress(Exception):
                aclose_coro = getattr(client, "aclose", None)
                if callable(aclose_coro):
                    await aclose_coro()

        text = text.strip()
        print(f"Groq transcription took {time.time() - cur_time:.2f} seconds; length={len(audio_bytes)} bytes")
        print(f"Groq transcription result: {text}")
        return text
    except Exception as e:
        print(f"Groq transcription error: {e}")
        return ""
    finally:
        with suppress(Exception):
            if wav_path and wav_path.exists():
                os.remove(str(wav_path))

async def generate_podcast_response(summary, conversation_history, user_question):
    """Generate response from both AI personas using GPT."""
    try:
        # Create conversation context
        conversation_text = "\n".join([f"{msg['speaker']}: {msg['text']}" for msg in conversation_history])
        
        system_prompt = f"""You are David (male) and Emma (female), two AI podcast hosts who were already having an engaging conversation about this topic: {summary}

You were interrupted when someone joined to ask a question. Now respond naturally as if you were continuing your conversation, but also address the user's question.

IMPORTANT RULES:
1. Both David and Emma should respond naturally and conversationally
2. They should acknowledge the user joining their ongoing conversation
3. Answer the user's question in an engaging, podcast-like manner
4. After answering, one of you should ask if the user has any more questions
5. If the user says "no" or indicates they don't have more questions, set disconnect_trigger to true
6. Keep responses natural and conversational, like real podcast hosts
7. You can have a short back-and-forth between yourselves before asking about more questions or even have only one of you respond
8. When the user has no more questions, you are to end the conversation. However when ending the conversation, follow this script:
    david: okay then. Im glad we could answer your questions. Now lets get back to what we were talking about
    emma: amazing.
User's question: {user_question}

Previous conversation context:
{conversation_text}

You MUST respond in this exact JSON format:
{{
    "responses": [
        {{
            "speaker": "David",
            "text": "David's response here"
        }},
        {{
            "speaker": "Emma", 
            "text": "Emma's response here"
        }}
    ],
    "disconnect_trigger": false
}}
make sure to set disconnect_trigger to true if the user indicates they don't have more questions and follow the ending conversation script provided above.
"""

        headers = {
            "Authorization": f"Bearer {get_openai_api_key()}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": "gpt-4o-mini",
            "messages": [
                {
                    "role": "system",
                    "content": system_prompt
                }
            ],
            "max_tokens": 300,
            "temperature": 0.8,
            "response_format": {"type": "json_object"}
        }
        
        async with aiohttp.ClientSession() as session:
            async with session.post(
                "https://api.openai.com/v1/chat/completions",
                headers=headers,
                json=payload,
                timeout=30
            ) as response:
                if response.status == 200:
                    result = await response.json()
                    response_content = result["choices"][0]["message"]["content"].strip()
                    
                    # Parse JSON response
                    try:
                        response_data = json.loads(response_content)

                        # Extract speaker messages
                        speaker_messages = []
                        for resp in response_data.get("responses", []):
                            speaker = resp.get("speaker", "")
                            text = resp.get("text", "")
                            if speaker and text:
                                speaker_messages.append({"speaker": speaker, "text": text})
                                conversation_history.append({"speaker": speaker, "text": text})
                        
                        # Convert speaker messages to audio
                        audio_messages = []
                        for resp in speaker_messages:
                            voice = "male" if resp["speaker"] == "David" else "female"
                            audio_messages.append({"text": resp["text"], "voice": voice})
                        
                        elevenlabs_response_audio = await generate_combined_ai_speech_with_elevenlabs(audio_messages)
                        
                        return response_data, elevenlabs_response_audio
                    except json.JSONDecodeError as e:
                        print(f"JSON parsing error: {e}")
                        return {}, ""
                else:
                    return []
    except Exception as e:
        print(f"Response generation error: {e}")
        return []


async def generate_combined_ai_speech_with_elevenlabs(messages):
    """Generate combined audio from multiple AI personas using ElevenLabs."""
    try:
        combined_audio_chunks = []
        
        for message in messages:
            print(f"Generating audio for {message['voice']} voice: {message['text']} time {time.time()}")
            voice_id = os.environ.get("ELEVENLABS_MALE_VOICE_ID") if message["voice"] == "male" else os.environ.get("ELEVENLABS_FEMALE_VOICE_ID")
            
            headers = {
                "xi-api-key": get_elevenlabs_api_key(),
                "Content-Type": "application/json"
            }
            
            payload = {
                "text": message["text"],
                "model_id": get_elevenlabs_model(),
                "voice_settings": {
                    "stability": 0.5,
                    "similarity_boost": 0.75,
                    "use_speaker_boost": True
                }
            }
            
            url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
            
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    url,
                    headers=headers,
                    json=payload,
                    timeout=15
                ) as response:
                    if response.status == 200:
                        audio_data = await response.read()
                        combined_audio_chunks.append(audio_data)
                    else:
                        print(f"ElevenLabs API error for {message['voice']} voice: {response.__dict__}")
        
        if combined_audio_chunks:
            # For simplicity, we'll concatenate the audio chunks
            # In a production system, you might want to add small silences between speakers
            combined_audio = b''.join(combined_audio_chunks)
            base64_audio = base64.b64encode(combined_audio).decode('utf-8')
            return base64_audio
        else:
            return ""
            
    except Exception as e:
        print(f"Combined audio generation error: {e}")
        return ""

@router.websocket("/ws/audio")
async def chatbot_websocket(websocket: WebSocket) -> None:

    await manager.connect(websocket)

    conv_session = InterractionSession(websocket)

    while True :
        message = await websocket.receive()

        if message.get("type") == "websocket.disconnect":
            print(f"client requested disconnect")
            break

        data = json.loads(message.get("text"))

        if data.get("type") == "summary":
            content = json.loads(data["content"])
            conv_session.summary = content["summary"]
            
        if data.get("type") == "audio":
            audio = data["audio"]
            pcm_array = audio["pcm16Array"]
            audio_int16 = np.array(pcm_array, dtype=np.int16)
            audio_bytes = audio_int16.tobytes()
            await conv_session.push_audio(audio_bytes)